// GENERATED by scripts/icons/build_solar_icons.py. Do not edit by hand:
// add the icon to scripts/icons/solar_icons.txt and re-run the script.
//
// Icons: Solar by 480 Design, CC BY 4.0.
// https://creativecommons.org/licenses/by/4.0/

import 'package:flutter/widgets.dart';

/// The Solar icon set as a font, for anywhere the app takes `IconData`.
///
/// Names keep Solar's style suffix: `Linear` is the outline style,
/// `Bold` the filled one.
class SolarIcons {
  const SolarIcons._();

  static const String _family = 'SolarIcons';

  /// solar:alt-arrow-down-linear
  static const IconData altArrowDownLinear = IconData(0xe000, fontFamily: _family);
  /// solar:alt-arrow-left-linear
  static const IconData altArrowLeftLinear = IconData(0xe001, fontFamily: _family);
  /// solar:alt-arrow-right-linear
  static const IconData altArrowRightLinear = IconData(0xe002, fontFamily: _family);
  /// solar:arrow-left-linear
  static const IconData arrowLeftLinear = IconData(0xe003, fontFamily: _family);
  /// solar:bicycling-linear
  static const IconData bicyclingLinear = IconData(0xe004, fontFamily: _family);
  /// solar:book-2-bold
  static const IconData book2Bold = IconData(0xe005, fontFamily: _family);
  /// solar:book-2-linear
  static const IconData book2Linear = IconData(0xe006, fontFamily: _family);
  /// solar:bus-linear
  static const IconData busLinear = IconData(0xe007, fontFamily: _family);
  /// solar:car-linear
  static const IconData carLinear = IconData(0xe008, fontFamily: _family);
  /// solar:chat-round-line-bold
  static const IconData chatRoundLineBold = IconData(0xe009, fontFamily: _family);
  /// solar:chat-round-line-linear
  static const IconData chatRoundLineLinear = IconData(0xe00a, fontFamily: _family);
  /// solar:check-circle-bold
  static const IconData checkCircleBold = IconData(0xe00b, fontFamily: _family);
  /// solar:check-linear
  static const IconData checkLinear = IconData(0xe00c, fontFamily: _family);
  /// solar:checklist-minimalistic-linear
  static const IconData checklistMinimalisticLinear = IconData(0xe00d, fontFamily: _family);
  /// solar:clock-circle-linear
  static const IconData clockCircleLinear = IconData(0xe00e, fontFamily: _family);
  /// solar:close-circle-bold
  static const IconData closeCircleBold = IconData(0xe00f, fontFamily: _family);
  /// solar:close-linear
  static const IconData closeLinear = IconData(0xe010, fontFamily: _family);
  /// solar:cloud-cross-linear
  static const IconData cloudCrossLinear = IconData(0xe011, fontFamily: _family);
  /// solar:crown-star-linear
  static const IconData crownStarLinear = IconData(0xe012, fontFamily: _family);
  /// solar:cup-star-bold
  static const IconData cupStarBold = IconData(0xe013, fontFamily: _family);
  /// solar:danger-circle-linear
  static const IconData dangerCircleLinear = IconData(0xe014, fontFamily: _family);
  /// solar:danger-triangle-linear
  static const IconData dangerTriangleLinear = IconData(0xe015, fontFamily: _family);
  /// solar:document-text-bold
  static const IconData documentTextBold = IconData(0xe016, fontFamily: _family);
  /// solar:document-text-linear
  static const IconData documentTextLinear = IconData(0xe017, fontFamily: _family);
  /// solar:dumbbell-large-linear
  static const IconData dumbbellLargeLinear = IconData(0xe018, fontFamily: _family);
  /// solar:eye-closed-linear
  static const IconData eyeClosedLinear = IconData(0xe019, fontFamily: _family);
  /// solar:eye-linear
  static const IconData eyeLinear = IconData(0xe01a, fontFamily: _family);
  /// solar:forbidden-circle-linear
  static const IconData forbiddenCircleLinear = IconData(0xe01b, fontFamily: _family);
  /// solar:gallery-linear
  static const IconData galleryLinear = IconData(0xe01c, fontFamily: _family);
  /// solar:gallery-remove-linear
  static const IconData galleryRemoveLinear = IconData(0xe01d, fontFamily: _family);
  /// solar:global-linear
  static const IconData globalLinear = IconData(0xe01e, fontFamily: _family);
  /// solar:headphones-round-sound-linear
  static const IconData headphonesRoundSoundLinear = IconData(0xe01f, fontFamily: _family);
  /// solar:heart-bold
  static const IconData heartBold = IconData(0xe020, fontFamily: _family);
  /// solar:heart-linear
  static const IconData heartLinear = IconData(0xe021, fontFamily: _family);
  /// solar:hourglass-linear
  static const IconData hourglassLinear = IconData(0xe022, fontFamily: _family);
  /// solar:info-circle-linear
  static const IconData infoCircleLinear = IconData(0xe023, fontFamily: _family);
  /// solar:letter-bold
  static const IconData letterBold = IconData(0xe024, fontFamily: _family);
  /// solar:letter-linear
  static const IconData letterLinear = IconData(0xe025, fontFamily: _family);
  /// solar:lightbulb-linear
  static const IconData lightbulbLinear = IconData(0xe026, fontFamily: _family);
  /// solar:list-check-linear
  static const IconData listCheckLinear = IconData(0xe027, fontFamily: _family);
  /// solar:list-linear
  static const IconData listLinear = IconData(0xe028, fontFamily: _family);
  /// solar:lock-keyhole-minimalistic-bold
  static const IconData lockKeyholeMinimalisticBold = IconData(0xe029, fontFamily: _family);
  /// solar:lock-keyhole-minimalistic-linear
  static const IconData lockKeyholeMinimalisticLinear = IconData(0xe02a, fontFamily: _family);
  /// solar:logout-2-linear
  static const IconData logout2Linear = IconData(0xe02b, fontFamily: _family);
  /// solar:magnifer-bug-linear
  static const IconData magniferBugLinear = IconData(0xe02c, fontFamily: _family);
  /// solar:magnifer-linear
  static const IconData magniferLinear = IconData(0xe02d, fontFamily: _family);
  /// solar:map-point-bold
  static const IconData mapPointBold = IconData(0xe02e, fontFamily: _family);
  /// solar:medal-ribbons-star-bold
  static const IconData medalRibbonsStarBold = IconData(0xe02f, fontFamily: _family);
  /// solar:menu-dots-bold
  static const IconData menuDotsBold = IconData(0xe030, fontFamily: _family);
  /// solar:pen-linear
  static const IconData penLinear = IconData(0xe031, fontFamily: _family);
  /// solar:question-circle-linear
  static const IconData questionCircleLinear = IconData(0xe032, fontFamily: _family);
  /// solar:question-square-bold
  static const IconData questionSquareBold = IconData(0xe033, fontFamily: _family);
  /// solar:record-linear
  static const IconData recordLinear = IconData(0xe034, fontFamily: _family);
  /// solar:refresh-linear
  static const IconData refreshLinear = IconData(0xe035, fontFamily: _family);
  /// solar:settings-bold
  static const IconData settingsBold = IconData(0xe036, fontFamily: _family);
  /// solar:shield-check-bold
  static const IconData shieldCheckBold = IconData(0xe037, fontFamily: _family);
  /// solar:square-academic-cap-bold
  static const IconData squareAcademicCapBold = IconData(0xe038, fontFamily: _family);
  /// solar:stopwatch-linear
  static const IconData stopwatchLinear = IconData(0xe039, fontFamily: _family);
  /// solar:text-square-bold
  static const IconData textSquareBold = IconData(0xe03a, fontFamily: _family);
  /// solar:text-square-linear
  static const IconData textSquareLinear = IconData(0xe03b, fontFamily: _family);
  /// solar:user-rounded-bold
  static const IconData userRoundedBold = IconData(0xe03c, fontFamily: _family);
  /// solar:user-rounded-linear
  static const IconData userRoundedLinear = IconData(0xe03d, fontFamily: _family);
  /// solar:walking-linear
  static const IconData walkingLinear = IconData(0xe03e, fontFamily: _family);
  /// solar:wi-fi-off-linear
  static const IconData wiFiOffLinear = IconData(0xe03f, fontFamily: _family);
}
