#!/usr/bin/env python3
"""Compile the Solar icons listed in solar_icons.txt into an icon font.

Outputs:
  assets/fonts/SolarIcons.ttf   the font
  lib/theme/solar_icons.dart    `SolarIcons.<name>` IconData constants

Why a font rather than SVGs: the app passes icons around as `IconData`
(topic icons, profile rows, result stats, image placeholders) and relies on
IconTheme for colour and size. A font keeps all of that working, so moving
from Material Icons is a one-token change per use.

Solar's Linear style draws with strokes; fonts need filled outlines, so each
SVG goes through picosvg (stroke -> fill) first.

Dev-only tools, not app dependencies:
  python3 -m venv .venv && .venv/bin/pip install picosvg fonttools
  .venv/bin/python scripts/icons/build_solar_icons.py

Icons: Solar by 480 Design, CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
Fetched from the Iconify API.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.svgLib.path import parse_path
from picosvg.svg import SVG

ROOT = Path(__file__).resolve().parents[2]
LIST = Path(__file__).with_name("solar_icons.txt")
FONT_OUT = ROOT / "assets/fonts/SolarIcons.ttf"
DART_OUT = ROOT / "lib/theme/solar_icons.dart"
FAMILY = "SolarIcons"
UPM = 1024
FIRST_CODEPOINT = 0xE000


def fetch(names):
    url = "https://api.iconify.design/solar.json?icons=" + ",".join(names)
    raw = subprocess.run(
        ["curl", "-sf", "-A", "Mozilla/5.0", url],
        capture_output=True, text=True, check=True,
    ).stdout
    data = json.loads(raw)
    aliases = data.get("aliases", {})
    out = {}
    for name in names:
        source = name if name in data["icons"] else aliases.get(name, {}).get("parent")
        if source not in data["icons"]:
            sys.exit(f"Solar icon not found: {name}")
        icon = data["icons"][source]
        w = icon.get("width", data.get("width", 24))
        h = icon.get("height", data.get("height", 24))
        out[name] = (w, h, icon["body"].replace("currentColor", "#000"))
    return out


def dart_name(name):
    head, *rest = name.split("-")
    ident = head + "".join(p[:1].upper() + p[1:] for p in rest)
    return re.sub(r"[^A-Za-z0-9]", "", ident)


def main():
    names = [l.strip() for l in LIST.read_text().splitlines()
             if l.strip() and not l.startswith("#")]
    names = sorted(dict.fromkeys(names))
    icons = fetch(names)

    glyph_order = [".notdef"]
    cmap, glyphs, metrics = {}, {}, {}
    notdef = TTGlyphPen(None)
    glyphs[".notdef"], metrics[".notdef"] = notdef.glyph(), (UPM, 0)

    for index, name in enumerate(names):
        w, h, body = icons[name]
        svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}">{body}</svg>'
        pico = SVG.fromstring(svg).topicosvg()
        pen = TTGlyphPen(None)
        # SVG is y-down in a w x h box; the font is y-up in a UPM square.
        scale = UPM / max(w, h)
        # TrueType stores quadratic curves only; Bold icons keep some cubics.
        quad = Cu2QuPen(pen, max_err=1.0)
        flip = TransformPen(quad, (scale, 0, 0, -scale, 0, UPM))
        for el in pico.svg_root.iter():
            if el.tag.endswith("path") and el.get("d"):
                parse_path(el.get("d"), flip)
        glyph_name = dart_name(name)
        glyph_order.append(glyph_name)
        glyphs[glyph_name] = pen.glyph()
        metrics[glyph_name] = (UPM, 0)
        cmap[FIRST_CODEPOINT + index] = glyph_name

    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    # The left side bearing must equal each glyph's real left edge. With 0
    # here, CoreText/Skia align the glyph's xMin to the origin and every icon
    # renders shifted left by its own margin (a back arrow visibly off-centre).
    glyf = fb.font["glyf"]
    metrics = {
        name: (advance, getattr(glyf[name], "xMin", 0))
        for name, (advance, _) in metrics.items()
    }
    fb.setupHorizontalMetrics(metrics)
    # Ascent = 1 em, descent = 0, like MaterialIcons, so Icon() centres the
    # glyph in its size x size box.
    fb.setupHorizontalHeader(ascent=UPM, descent=0)
    fb.setupNameTable({"familyName": FAMILY, "styleName": "Regular"})
    fb.setupOS2(sTypoAscender=UPM, sTypoDescender=0, sTypoLineGap=0,
                usWinAscent=UPM, usWinDescent=0)
    fb.setupPost()
    FONT_OUT.parent.mkdir(parents=True, exist_ok=True)
    fb.save(str(FONT_OUT))

    lines = [
        "// GENERATED by scripts/icons/build_solar_icons.py. Do not edit by hand:",
        "// add the icon to scripts/icons/solar_icons.txt and re-run the script.",
        "//",
        "// Icons: Solar by 480 Design, CC BY 4.0.",
        "// https://creativecommons.org/licenses/by/4.0/",
        "",
        "import 'package:flutter/widgets.dart';",
        "",
        "/// The Solar icon set as a font, for anywhere the app takes `IconData`.",
        "///",
        "/// Names keep Solar's style suffix: `Linear` is the outline style,",
        "/// `Bold` the filled one.",
        "class SolarIcons {",
        "  const SolarIcons._();",
        "",
        f"  static const String _family = '{FAMILY}';",
        "",
    ]
    for index, name in enumerate(names):
        lines.append(f"  /// solar:{name}")
        lines.append(
            f"  static const IconData {dart_name(name)} ="
            f" IconData(0x{FIRST_CODEPOINT + index:x}, fontFamily: _family);"
        )
    lines.append("}")
    DART_OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(names)} icons -> {FONT_OUT.relative_to(ROOT)}, {DART_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
