// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7dyK2oMy7NKeVt9sMDxlsgOcTGQwAXFc',
    appId: '1:987638335534:web:d0f5efb48f240e567937bf',
    messagingSenderId: '987638335534',
    projectId: 'licenseprepapp',
    authDomain: 'licenseprepapp.firebaseapp.com',
    storageBucket: 'licenseprepapp.appspot.com',
    measurementId: 'G-8TTZX72V8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3NFSey7JrJHEAejCKrzBWSqrpJg6HMoY',
    appId: '1:987638335534:android:4a3c520893b3e6f67937bf',
    messagingSenderId: '987638335534',
    projectId: 'licenseprepapp',
    storageBucket: 'licenseprepapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ3RikKC1X7bRvVYYUM6qAVfTdfm0cz9k',
    appId: '1:987638335534:ios:5906bcc4cfcac9337937bf',
    messagingSenderId: '987638335534',
    projectId: 'licenseprepapp',
    storageBucket: 'licenseprepapp.firebasestorage.app',
    iosBundleId: 'com.driveusa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ3RikKC1X7bRvVYYUM6qAVfTdfm0cz9k',
    appId: '1:987638335534:ios:da18bab6faa1b2187937bf',
    messagingSenderId: '987638335534',
    projectId: 'licenseprepapp',
    storageBucket: 'licenseprepapp.firebasestorage.app',
    iosBundleId: 'com.example.licensePrepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7dyK2oMy7NKeVt9sMDxlsgOcTGQwAXFc',
    appId: '1:987638335534:web:87b69a558a1608fb7937bf',
    messagingSenderId: '987638335534',
    projectId: 'licenseprepapp',
    authDomain: 'licenseprepapp.firebaseapp.com',
    storageBucket: 'licenseprepapp.firebasestorage.app',
    measurementId: 'G-1Y1BQ616EK',
  );
}